name: Run Data Pipelines in GBQ
on:
    push:
        branches: [main]
    schedule:
        # everyday at 5:00 AM
        - cron: '0 5 * * *'
jobs:
    run-pipeline:
        name: Run Pipeline
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: read
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            - name: Google Auth
              uses: google-github-actions/auth@v1.1.1
              with:
                workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
                service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
                create_credentials_file: true
                access_token_lifetime: '300s'
                token_format: 'id_token'
                id_token_audience: 'projects/536240501365/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
            - name: Run pipeline
              run: |
                    python src/extract.py